using ZCodex.Core.Models;

namespace ZCodex.App.Views;

/// <summary>
/// Une ligne d'aide : un geste / chemin de menu (colonne de gauche) et sa description
/// (colonne de droite), dans les deux langues. <see cref="Key"/> et <see cref="Desc"/>
/// résolvent la langue courante A LA LECTURE — la bascule FR/EN se fait donc en rebindant
/// la liste (cf. HelpWindow.RefreshLanguage), pas en reconstruisant les données.
/// </summary>
public sealed record HelpRow(string KeyFr, string KeyEn, string DescFr, string DescEn)
{
    public string Key => AppLanguage.IsFr ? KeyFr : KeyEn;
    public string Desc => AppLanguage.IsFr ? DescFr : DescEn;
}

/// <summary>Un bloc de l'aide : titre, note d'introduction facultative, et ses lignes.</summary>
public sealed record HelpSection(string TitleFr, string TitleEn, string NoteFr, string NoteEn, HelpRow[] Rows)
{
    public string Title => AppLanguage.IsFr ? TitleFr : TitleEn;
    public string Note => AppLanguage.IsFr ? NoteFr : NoteEn;
    public bool HasNote => Note.Length > 0;
}

/// <summary>
/// Contenu de la fenêtre d'aide : catalogue des menus, actions, raccourcis et gestes souris.
/// Une feature = UNE ligne portant ses deux langues côte à côte (pas de clés dans
/// Strings.fr|en.xaml : ici le FR et l'EN se relisent d'un coup d'oeil et ne peuvent pas
/// diverger). Ajouter une feature = ajouter un <see cref="HelpRow"/> dans la bonne section,
/// puis incrémenter <see cref="VersionFr"/>/<see cref="VersionEn"/>.
/// </summary>
public static class HelpContent
{
    // Version du CONTENU de l'aide (indépendante de la version applicative de l'À propos) :
    // à incrémenter et redater à chaque mise à jour.
    public const string VersionFr = "Aide v4 — 21/08/2026";
    public const string VersionEn = "Help v4 — 2026-08-21";

    public static string Version => AppLanguage.IsFr ? VersionFr : VersionEn;

    public static string WindowTitle => AppLanguage.IsFr
        ? "Z-Codex — Aide et raccourcis"
        : "Z-Codex — Help and shortcuts";

    public static string Title => AppLanguage.IsFr ? "Aide et raccourcis" : "Help and shortcuts";

    public static string Intro => AppLanguage.IsFr
        ? "Toutes les actions de Z-Codex, classées par zone de l'interface. Les gestes clavier et souris sont indiqués dans la colonne de gauche."
        : "Every action in Z-Codex, grouped by area of the interface. Keyboard and mouse gestures are listed in the left column.";

    // Séparateur de sous-menu (Fichier > Ouvrir...).
    private const string M = " ▸ ";

    private static HelpRow R(string keyFr, string keyEn, string descFr, string descEn)
        => new(keyFr, keyEn, descFr, descEn);

    private static HelpSection S(string titleFr, string titleEn, string noteFr, string noteEn, params HelpRow[] rows)
        => new(titleFr, titleEn, noteFr, noteEn, rows);

    public static readonly HelpSection[] Sections =
    {
        // ═══════════════ MENUS ═══════════════
        S("Menus — Fichier et Édition", "Menus — File and Edit",
          "Le symbole ▸ désigne un sous-menu.",
          "The ▸ symbol denotes a submenu.",
            R("Fichier" + M + "Nouveau teambuild", "File" + M + "New Teambuild",
              "Crée un team build vide (onglet éditeur multi-personnages).",
              "Creates an empty team build (multi-character editor tab)."),
            R("Fichier" + M + "Nouveau template de build", "File" + M + "New Build Template",
              "Ouvre un éditeur de build simple (un personnage), enregistrable en template de compétences .txt.",
              "Opens a single-character build editor, saveable as a .txt skill template."),
            R("Fichier" + M + "Nouveau template d'équipement", "File" + M + "New Equipment Template",
              "Ouvre l'éditeur d'équipement pour composer un nouveau code d'équipement (P).",
              "Opens the equipment editor to compose a new equipment code (P)."),
            R("Fichier" + M + "Ouvrir…", "File" + M + "Open…",
              "Ouvre un fichier de team build (.pn3, .pwnd) ou un template (.txt) dans un onglet.",
              "Opens a team build file (.pn3, .pwnd) or a template (.txt) in a tab."),
            R("Fichier" + M + "Enregistrer — Ctrl+S", "File" + M + "Save — Ctrl+S",
              "Enregistre l'onglet actif : team build (.zcx) ou build simple (template .txt). Réécrit le fichier d'origine, et ne demande un emplacement que s'il n'y en a pas encore.",
              "Saves the active tab: team build (.zcx) or single build (.txt template). Overwrites the original file, and only asks for a location if there is not one yet."),
            R("Fichier" + M + "Enregistrer sous… — Ctrl+Shift+S", "File" + M + "Save as… — Ctrl+Shift+S",
              "Enregistre l'onglet actif sous un nouveau nom ou emplacement, dans les deux vues.",
              "Saves the active tab under a new name or location, in both views."),
            R("Fichier" + M + "Exporter en paw·ned² (.pwnd)", "File" + M + "Export to paw·ned² (.pwnd)",
              "Écrit le team build actif au format de paw·ned², en trois portées : tout le teambuild (variantes comprises), les 8 premiers personnages, ou un cadenas. Ce que le format ne transporte pas est détaillé plus bas, dans « Fichiers, formats et données ».",
              "Writes the active team build in paw·ned²'s format, in three scopes: the whole team build (variants included), the first 8 characters, or one lock. What the format cannot carry is spelled out below, under “Files, formats and data”."),
            R("Fichier" + M + "Quitter", "File" + M + "Exit",
              "Quitte l'application. Propose d'enregistrer les builds modifiés non sauvegardés.",
              "Quits the application. Offers to save any modified, unsaved builds."),
            R("Édition" + M + "Annuler — Ctrl+Z", "Edit" + M + "Undo — Ctrl+Z",
              "Annule la dernière modification de l'onglet actif, team build ou Build. Une rafale rapide (≤ 0,5 s) compte pour un seul pas. Dans un onglet Build, l'historique couvre exactement ce qu'un .txt enregistre : professions, compétences, points d'attribut (pas le flux, les rituels ni les rangs de titre, volatils).",
              "Undoes the last change to the active tab, team build or Build. A quick burst (≤ 0.5 s) counts as a single step. In a Build tab the history covers exactly what a .txt stores: professions, skills, attribute points (not flux, rituals or title ranks, which are volatile)."),
            R("Édition" + M + "Rétablir — Ctrl+Y", "Edit" + M + "Redo — Ctrl+Y",
              "Rétablit l'action précédemment annulée. La pile d'annulation est propre à chaque onglet.",
              "Redoes the previously undone action. The undo stack belongs to each tab."),
            R("Édition" + M + "Copier le template de compétences (O) / au format chat",
              "Edit" + M + "Copy skill template (O) / as chat code",
              "Copie le code du build édité dans le presse-papier, brut ou au format chat « [1 Mo/N - nom;code] ». Actif dans un onglet Build ; dans un team build, la copie se fait par personnage (Ctrl+C, icône ⧉, ou clic droit sur la ligne).",
              "Copies the edited build's code to the clipboard, raw or as a chat code “[1 Mo/N - name;code]”. Enabled in a Build tab; in a team build, copying is done per character (Ctrl+C, ⧉ icon, or right-click on the row)."),
            R("Édition" + M + "Importer un template depuis le presse-papier",
              "Edit" + M + "Import a template from the clipboard",
              "Applique le code GW1 du presse-papier — brut (OwQTU2n…) ou code de chat ([nom;OwQTU2n…]), de compétences (O) et/ou d'équipement (P). Onglet Build : dans le build édité. Team build : dans le 1er personnage vide, sinon dans une nouvelle ligne.",
              "Applies the GW1 code held in the clipboard — raw (OwQTU2n…) or chat code ([name;OwQTU2n…]), skills (O) and/or equipment (P). Build tab: into the edited build. Team build: into the first empty character, otherwise into a new row."),
            R("Édition" + M + "Importer un template depuis un fichier…",
              "Edit" + M + "Import a template from a file…",
              "Même import, depuis un .txt de template GW1 — indépendant du presse-papier, donc toujours accessible même quand celui-ci contient déjà un code. Ces entrées sont aussi au clic droit : dans la page d'un onglet Build, et sur une ligne de personnage d'un team build.",
              "Same import, from a GW1 template .txt — independent of the clipboard, so always reachable even when the clipboard already holds a code. These entries are also on right-click: in the page of a Build tab, and on a team build character row."),
            R("Ctrl+C / Ctrl+V", "Ctrl+C / Ctrl+V",
              "Copient / importent le template du personnage SURVOLÉ par la souris — la ligne pointée dans un team build, le build édité dans un onglet Build. Un champ de saisie garde son copier-coller de texte habituel.",
              "Copy / import the template of the character UNDER THE MOUSE — the row you point at in a team build, the edited build in a Build tab. A focused text field keeps its usual text copy-paste.")),

        S("Menus — Affichage", "Menus — View",
          "Ces réglages sont mémorisés entre les sessions.",
          "These settings are remembered between sessions.",
            R("Affichage" + M + "Afficher les attributs", "View" + M + "Show attributes",
              "Affiche ou masque l'éditeur d'attributs sous chaque personnage du team build.",
              "Shows or hides the attribute editor under each team build character."),
            R("Affichage" + M + "Molette : sélectionner le personnage d'abord",
              "View" + M + "Wheel: select the character first",
              "Sécurise la molette dans un team build : tant qu'aucun personnage n'a été cliqué (liseré bleu), elle ne fait que défiler la vue, et une fois un personnage actif elle ne règle les caractéristiques que sur celui-là. Décochée, la molette agit sur le personnage survolé, sans clic préalable.",
              "Makes the wheel safe in a team build: until a character has been clicked (blue edge) it only scrolls the view, and once one is active it sets attributes on that character alone. Unticked, the wheel acts on whichever character is hovered, with no click needed."),
            R("Affichage" + M + "Afficher le filtre Types de compétences / Afficher le filtre Mécaniques",
              "View" + M + "Show the Skill Types filter / Show the Mechanics filter",
              "Affichent ou masquent les deux lignes de filtres du catalogue, indépendamment l'une de l'autre (voir « Catalogue de compétences »). Masquer un filtre remet CE filtre-là sur « All ». Les mêmes cases se trouvent dans la barre de recherche de chaque catalogue.",
              "Show or hide the catalog's two filter rows, independently of each other (see “Skill catalog”). Hiding a filter resets THAT filter to “All”. The same tick boxes sit in every catalog's search bar."),
            R("Affichage" + M + "Afficher les caractéristiques dans la preview",
              "View" + M + "Show attributes in the preview",
              "Superpose le niveau des caractéristiques investies sur les icônes de la preview du browser.",
              "Overlays the invested attribute ranks on the icons of the browser preview."),
            R("Affichage" + M + "Afficher les conditions", "View" + M + "Show conditions",
              "Affiche ou masque les bandeaux de conditions infligeables (sous le build dans l'éditeur, ligne unique au-dessus du team build).",
              "Shows or hides the inflictable-condition bars (under the build in the editor, single row above the team build)."),
            R("Affichage" + M + "Afficher les dégâts selon l'armure", "View" + M + "Show armor-based damage",
              "Ajoute à l'infobulle de compétence, dans un build, la table des dégâts théoriques par niveau d'armure.",
              "Adds the theoretical damage-per-armor-level table to the skill tooltip inside a build."),
            R("Affichage" + M + "Dégâts selon l'armure…", "View" + M + "Armor-based damage…",
              "Paramètres de cette table : jusqu'à 8 colonnes d'AL (0–200, bouton « + », champ vide = colonne retirée), niveau du personnage (1–20) et niveau de la cible (1–40, taux de critique).",
              "Settings for that table: up to 8 AL columns (0–200, “+” button, empty field = column removed), character level (1–20) and target level (1–40, critical hit rate)."),
            R("Affichage" + M + "Afficher la barre des Rituels de la Nature",
              "View" + M + "Show Nature Rituals bar",
              "Affiche ou masque le bandeau d'icônes des Rituels de la Nature (éditeur et team build).",
              "Shows or hides the Nature Rituals icon bar (editor and team build)."),
            R("Affichage" + M + "Afficher tous les Rituels de la Nature",
              "View" + M + "Show all Nature Rituals",
              "Affiche les 8 rituels simulables dans le bandeau, même ceux qu'aucun personnage n'a équipés.",
              "Shows all 8 simulated rituals in the bar, including those no character has equipped."),
            R("Affichage" + M + "Taille des icônes" + M + "Grande / Moyenne / Petite",
              "View" + M + "Icon size" + M + "Large / Medium / Small",
              "Taille des slots de compétences : 64, 52 ou 40 px — gain de place à l'écran.",
              "Skill slot size: 64, 52 or 40 px — saves screen space."),
            R("Affichage" + M + "Thème sombre", "View" + M + "Dark theme",
              "Bascule l'interface entre thème clair et thème sombre.",
              "Switches the interface between light and dark theme."),
            R("Affichage" + M + "Langue" + M + "Français / English", "View" + M + "Language" + M + "Français / English",
              "Change la langue de l'interface ET du catalogue (noms et descriptions de compétences), immédiatement, sans redémarrer.",
              "Changes the language of the interface AND of the catalog (skill names and descriptions), immediately, without restarting."),
            R("Affichage" + M + "Prendre un screenshot…", "View" + M + "Take a screenshot…",
              "Exporte une image (.png) de la grille du team build actif.",
              "Exports an image (.png) of the active team build grid.")),

        S("Menus — Sélection, Extras, Fenêtre, Aide", "Menus — Selection, Extras, Window, Help", "", "",
            R("Sélection" + M + "Ouvrir le build sélectionné", "Selection" + M + "Open selected build",
              "Ouvre le fichier sélectionné dans le browser (équivaut à un double-clic).",
              "Opens the file selected in the browser (same as a double-click)."),
            R("Sélection" + M + "Flux", "Selection" + M + "Flux",
              "Active l'un des 12 flux du cycle (le flux du mois courant est signalé) ou aucun. Le flux actif s'applique aux infobulles, aux attributs et au calcul de spike du build.",
              "Activates one of the 12 flux of the cycle (the current month's flux is flagged) or none. The active flux applies to the build's tooltips, attributes and spike calculus."),
            R("Sélection" + M + "Rituels de la Nature (énergie/recharge)",
              "Selection" + M + "Nature Rituals (energy/recharge)",
              "Active ou désactive chacun des 8 rituels simulés. C'est un environnement GLOBAL : il s'applique aux infobulles de tous les personnages du build.",
              "Toggles each of the 8 simulated rituals. This is a GLOBAL environment: it applies to the tooltips of every character in the build."),
            R("Extras" + M + "Mettre à jour les compétences (wiki)", "Extras" + M + "Update skill database (wiki)",
              "Re-télécharge le catalogue depuis le Guild Wars Wiki (stats, icônes, tables de progression, conditions, noms et descriptions FR). Peut durer plusieurs minutes.",
              "Re-downloads the catalog from the Guild Wars Wiki (stats, icons, progression tables, conditions, French names and descriptions). May take several minutes."),
            R("Extras" + M + "GW1 Builds", "Extras" + M + "GW1 Builds",
              "Ouvre gw1builds.com dans le navigateur.", "Opens gw1builds.com in the browser."),
            R("Extras" + M + "GW PvX Fandom Wiki", "Extras" + M + "GW PvX Fandom Wiki",
              "Ouvre le wiki PvX (gwpvx.fandom.com) dans le navigateur.",
              "Opens the PvX wiki (gwpvx.fandom.com) in the browser."),
            R("Extras" + M + "Calculateur d'armure", "Extras" + M + "Armor calculator",
              "Ouvre l'onglet Armure (voir « Calculateur d'armure »).",
              "Opens the Armor tab (see “Armor calculator”)."),
            R("Extras" + M + "Télécharger les builds PvX…", "Extras" + M + "Download PvX builds…",
              "Récupère les build packs publiés par PvXwiki — les builds validés par la communauté, en codes de template lisibles par Z-Codex comme par le jeu. Au choix : les builds PvE (~2 170 fichiers), les PvP (~1 090), ou les deux, dans le dossier que vous désignez. Chaque archive crée son propre sous-dossier ; les équipes d'au plus 8 barres sont assemblées en .zcx, les autres restent en .txt.",
              "Fetches the build packs published by PvXwiki — the community's vetted builds, as template codes readable by Z-Codex and by the game alike. Your pick: PvE builds (~2,170 files), PvP builds (~1,090), or both, into the folder you choose. Each archive creates its own subfolder; teams of at most 8 bars are assembled as .zcx, the rest stay .txt."),
            R("Extras" + M + "Vérifier les icônes (wiki)", "Extras" + M + "Check icons (wiki)",
              "Contrôle les icônes d'interface (professions, coûts, conditions, flux, vol de vie) et re-télécharge celles qui manquent ou sont illisibles, puis annonce le résultat. Les icônes de COMPÉTENCES, elles, viennent de « Mettre à jour les compétences ». Un redémarrage les remet partout.",
              "Checks the interface icons (professions, costs, conditions, flux, life stealing), downloads again those missing or unreadable, then reports what it did. SKILL icons come from “Update skill database” instead. A restart shows them everywhere."),
            R("Extras" + M + "Recalculer les catégories de compétences",
              "Extras" + M + "Recompute skill categories",
              "Réécrit dans la base les mécaniques de jeu déduites de chaque compétence et indique combien de lignes ont changé. Utile après une mise à jour du catalogue ; l'affichage, lui, refait déjà ce calcul à chaque démarrage.",
              "Rewrites into the database the game mechanics deduced for each skill and reports how many rows changed. Useful after a catalog update; the display itself already redoes that calculation at every start."),
            R("Fenêtre" + M + "…", "Window" + M + "…",
              "Liste les onglets ouverts et permet de basculer entre eux ou d'activer l'onglet Team Builds. Contient aussi « Fermer l'onglet actif ».",
              "Lists the open tabs and lets you switch between them or activate the Team Builds tab. Also holds “Close active tab”."),
            R("Aide" + M + "Aide et raccourcis… — F1", "Help" + M + "Help and shortcuts… — F1",
              "Ouvre cette fenêtre.", "Opens this window."),
            R("Aide" + M + "Rechercher les mises à jour…", "Help" + M + "Check for updates…",
              "Demande à GitHub si une version plus récente de Z-Codex est publiée, et propose d'ouvrir sa page de téléchargement. Le même contrôle a lieu au démarrage : Z-Codex signale, mais n'installe jamais rien de lui-même.",
              "Asks GitHub whether a newer Z-Codex has been published, and offers to open its download page. The same check runs at startup: Z-Codex tells you, but never installs anything by itself."),
            R("Aide" + M + "À propos de Z-Codex…", "Help" + M + "About Z-Codex…",
              "Version de l'application, crédits, remerciements aux testeurs et lien Discord pour les retours, bugs et idées de fonctionnalités.",
              "Application version, credits, thanks to the testers and a Discord link for feedback, bug reports and feature ideas.")),

        // ═══════════════ BARRE D'OUTILS + ONGLETS ═══════════════
        S("Barre d'outils", "Toolbar",
          "Boutons sous la barre de menus. Survolez un bouton pour voir son libellé.",
          "Buttons under the menu bar. Hover a button to see its label.",
            R("Nouveau teambuild", "New team build",
              "Crée un team build vide.", "Creates an empty team build."),
            R("Nouveau template de build", "New build template",
              "Ouvre un éditeur de build simple.", "Opens a single-character build editor."),
            R("Ouvrir", "Open",
              "Ouvre un fichier de build ou de template.", "Opens a build or template file."),
            R("Enregistrer", "Save",
              "Enregistre l'onglet actif, team build ou build simple.",
              "Saves the active tab, team build or single build."),
            R("Chercher des compétences dans les templates", "Search templates for skills",
              "Ouvre l'onglet de recherche (voir « Recherche de templates »).",
              "Opens the search tab (see “Template search”)."),
            R("Partager le build", "Share build",
              "Ouvre un menu vers les deux sites de builds : GW1 Builds et GW PvX Fandom Wiki (mêmes entrées que le menu Extras).",
              "Opens a menu to the two build sites: GW1 Builds and GW PvX Fandom Wiki (same entries as the Extras menu).")),

        S("Onglets", "Tabs",
          "L'onglet « Team Builds » (le browser) est fixe et ne peut pas être fermé. Les autres onglets sont les team builds, les éditeurs de build simple, les résultats de recherche et le calculateur d'armure.",
          "The “Team Builds” tab (the browser) is fixed and cannot be closed. The other tabs are team builds, single build editors, search results and the armor calculator.",
            R("Clic", "Click", "Active l'onglet.", "Activates the tab."),
            R("Clic sur ✕ / Clic milieu / Double-clic", "Click ✕ / Middle-click / Double-click",
              "Ferme l'onglet. Si le build a des modifications non enregistrées, une confirmation est demandée.",
              "Closes the tab. If the build has unsaved changes, a confirmation is asked."),
            R("Clic droit", "Right-click",
              "Menu de l'onglet : Renommer, Fermer.", "Tab menu: Rename, Close."),
            R("Onglet Armure", "Armor tab",
              "Se ferme par son ✕ mais garde son état : le rouvrir depuis Extras retrouve les réglages en cours.",
              "Closes with its ✕ but keeps its state: reopening it from Extras restores the current settings.")),

        // ═══════════════ BARRE DE COMPÉTENCES ═══════════════
        S("Éditeur — barre de compétences (8 slots)", "Editor — skill bar (8 slots)",
          "Rangée de 8 slots par personnage. L'ordre des compétences n'est pas imposé. Survolez un slot pour l'infobulle détaillée.",
          "A row of 8 slots per character. Skill order is free. Hover a slot for the detailed tooltip.",
            R("Glisser depuis le catalogue", "Drag from the catalog",
              "Dépose la compétence dans le slot (copie).", "Drops the skill into the slot (copy)."),
            R("Glisser d'un slot à un autre", "Drag from one slot to another",
              "Échange les deux slots (déplacement).", "Swaps the two slots (move)."),
            R("Shift ou Ctrl en déposant", "Shift or Ctrl while dropping",
              "Copie la compétence au lieu de l'échanger (la source reste en place).",
              "Copies the skill instead of swapping (the source stays in place)."),
            R("Ctrl + Shift en déposant", "Ctrl + Shift while dropping",
              "Copie la compétence ET le niveau de caractéristique correspondant du personnage source.",
              "Copies the skill AND the matching attribute rank from the source character."),
            R("Glisser hors de la barre", "Drag out of the bar",
              "Vide le slot (supprime la compétence).", "Clears the slot (removes the skill)."),
            R("Suppr", "Delete",
              "Vide le slot sous le curseur (le slot doit avoir le focus, cliquez-le d'abord).",
              "Clears the slot under the cursor (the slot must have focus, click it first)."),
            R("Clic droit sur un slot", "Right-click a slot",
              "Menu : Article de la compétence (wiki), Page de discussion, Chercher dans les templates, Supprimer la compétence.",
              "Menu: Skill article (wiki), Skill discussion, Parse in templates, Remove skill."),
            R("Cadre rouge sur un slot", "Red frame on a slot",
              "Signale une compétence qui n'appartient ni à la profession primaire ni à la secondaire du personnage (allégeances Kurzick/Luxon comprises).",
              "Flags a skill belonging to neither the character's primary nor secondary profession (Kurzick/Luxon allegiance skills included).")),

        // ═══════════════ INFOBULLE ═══════════════
        S("Infobulle de compétence", "Skill tooltip",
          "Survolez un slot ou une ligne du catalogue. Dans un build, l'infobulle est calculée pour CE personnage : rangs investis, équipement, flux et rituels actifs.",
          "Hover a slot or a catalog row. Inside a build the tooltip is computed for THAT character: invested ranks, equipment, active flux and rituals.",
            R("En-tête", "Header",
              "Icône (cadre or = compétence élite), identifiant GW1, nom et ligne de type.",
              "Icon (gold frame = elite skill), GW1 id, name and type line."),
            R("Bandeau de coûts", "Cost strip",
              "Énergie, adrénaline, sacrifice, surchauffe, entretien, temps d'activation et recharge, avec les icônes du wiki.",
              "Energy, adrenaline, sacrifice, overcast, upkeep, activation time and recharge, with the wiki icons."),
            R("Description", "Description",
              "Valeurs résolues au rang du personnage et affichées en vert. Dans le catalogue (pas de personnage), la plage 0…15… reste affichée.",
              "Values resolved at the character's rank and shown in green. In the catalog (no character), the range is shown instead."),
            R("Pied de l'infobulle", "Tooltip footer",
              "Effet du bonus d'attribut primaire de la profession, au rang courant.",
              "Effect of the profession's primary attribute bonus, at the current rank."),
            R("Coût « réduit (base) »", "“reduced (base)” cost",
              "L'Expertise du Rôdeur abaisse le coût en énergie des attaques, compétences de toucher et rituels : la valeur de base reste lisible entre parenthèses.",
              "Ranger Expertise lowers the energy cost of attacks, touch skills and rituals: the base value stays readable in parentheses."),
            R("Valeurs en ambre", "Amber values",
              "Un Rituel de la Nature actif modifie l'énergie, la recharge, l'activation, l'entretien ou la surchauffe. La ligne « Durée d'enchantement effective » suit la même couleur.",
              "An active Nature Ritual changes energy, recharge, activation, upkeep or overcast. The “effective enchantment duration” line uses the same color."),
            R("Table de dégâts", "Damage table",
              "Si « Afficher les dégâts selon l'armure » est activé : dégâts par niveau d'armure, pénétration comprise. Pour les attaques d'arme : plage totale (arme customisée, rang de maîtrise) et coup critique avec son taux.",
              "If “Show armor-based damage” is on: damage per armor level, penetration included. For weapon attacks: full range (customized weapon, mastery rank) and critical hit with its rate."),
            R("Bloc « Invocation »", "“Spawning” block",
              "Pour un Ritualiste : effet de la Puissance de l'invocation — durée des sorts d'arme, PV, armure et durée de vie des esprits et serviteurs.",
              "For a Ritualist: effect of Spawning Power — weapon spell duration, health, armor and lifespan of spirits and minions.")),

        // ═══════════════ ATTRIBUTS ═══════════════
        S("Attributs — molette de la souris", "Attributes — mouse wheel",
          "Placez le curseur sur un slot de compétence (ou sur une ligne de l'éditeur d'attributs) et actionnez la molette. La caractéristique visée est celle de la compétence survolée. Fonctionne même quand l'éditeur d'attributs est replié.",
          "Put the cursor on a skill slot (or on a row of the attribute editor) and use the wheel. The attribute targeted is the one of the hovered skill. Works even when the attribute editor is collapsed.",
            R("Molette", "Wheel",
              "Niveau de la caractéristique de la compétence survolée (0–12, déborde sur le bonus au-delà).",
              "Rank of the hovered skill's attribute (0–12, overflows into the bonus beyond that)."),
            R("Shift + molette", "Shift + wheel",
              "Bonus de niveau (runes, coiffe, consommables) de cette caractéristique — hors budget.",
              "Rank bonus (runes, headgear, consumables) for that attribute — outside the budget."),
            R("Ctrl + molette", "Ctrl + wheel",
              "Niveau de l'attribut primaire du personnage.", "Rank of the character's primary attribute."),
            R("Ctrl + Shift + molette", "Ctrl + Shift + wheel",
              "Bonus de niveau de l'attribut primaire.", "Rank bonus of the primary attribute."),
            R("Alt + molette", "Alt + wheel",
              "Saute au « hard breakpoint » suivant/précédent de la caractéristique (niveau où une valeur change). Sans breakpoint exploitable, ne fait rien.",
              "Jumps to the next/previous hard breakpoint of the attribute (rank where a value changes). Does nothing when there is no usable breakpoint."),
            R("Alt + Shift + molette", "Alt + Shift + wheel",
              "Idem, mais sur le niveau effectif (base + bonus, jusqu'à 20).",
              "Same, but on the effective rank (base + bonus, up to 20)."),
            R("Boutons − / + (ligne d'attribut)", "− / + buttons (attribute row)",
              "Diminuent / augmentent le niveau de la caractéristique d'un cran.",
              "Decrease / increase the attribute rank by one step."),
            R("Second spinner « bonus » (onglet Build)", "Second “bonus” spinner (Build tab)",
              "Dans le cadre d'attributs de l'onglet Build, chaque ligne a un second couple − / + qui règle le seul niveau bonus (runes, coiffe, consommables), hors budget ; Shift + molette sur la ligne fait la même chose. Le total « = » à droite donne le niveau effectif. Les rangs de titre n'en ont pas.",
              "In the Build tab's attribute box, each row has a second − / + pair that sets the rank bonus alone (runes, headgear, consumables), outside the budget; Shift + wheel on the row does the same. The “=” total on the right shows the effective rank. Title ranks have none.")),

        S("Attributs — lecture du panneau", "Attributes — reading the panel", "", "",
            R("Compteur « x/200 »", "“x/200” counter",
              "Points d'attribut dépensés ; passe en rouge et gras si le budget est dépassé.",
              "Attribute points spent; turns red and bold if the budget is exceeded."),
            R("Rangs de titre", "Title ranks",
              "Les pistes PvE (Lanciers du Soleil, Asura…) apparaissent dès qu'une compétence posée les utilise. Elles sont hors budget et sans bonus de rune.",
              "PvE tracks (Sunspear, Asura…) appear as soon as an equipped skill uses them. They are outside the budget and take no rune bonus."),
            R("Case « mod of the »", "“mod of the” box",
              "Éditeur de build simple : simule un mod d'arme « of the <profession> », qui porte la caractéristique primaire de la profession choisie à 5.",
              "Single build editor: simulates an “of the <profession>” weapon mod, which sets that profession's primary attribute to 5."),
            R("Filtre PvP", "PvP filter",
              "Avec le catalogue en « PvP only », aucun bonus de joueur n'est admis sur les caractéristiques secondaires : les bonus posés sont purgés et bloqués.",
              "With the catalog set to “PvP only”, no player bonus is allowed on secondary attributes: existing bonuses are cleared and blocked."),
            R("Couleurs du récap", "Summary colors",
              "Vert = valeur résolue ; violet = bonus d'une compétence activée ; ambre = valeur imposée (« Fixé à X », Maître de la magie) ou modifiée par un rituel.",
              "Green = resolved value; purple = bonus from an activated skill; amber = forced value (“Fixed at X”, Master of Magic) or ritual-modified.")),

        // ═══════════════ PERSONNAGE ═══════════════
        S("Personnage (panneau de gauche)", "Character (left panel)", "", "",
            R("Clic sur l'icône de profession", "Click a profession icon",
              "Ouvre le sélecteur de profession primaire / secondaire. Choisir dans l'autre picker échange PR/SEC ; « Aucune » retire la secondaire.",
              "Opens the primary / secondary profession picker. Picking in the other one swaps them; “None” removes the secondary."),
            R("⇄ (bouton)", "⇄ (button)",
              "Échange profession primaire et secondaire (les points de l'ancienne primaire sont remis à zéro).",
              "Swaps primary and secondary profession (the old primary's points are reset)."),
            R("Clic sur l'étoile (★ / ☆)", "Click the star (★ / ☆)",
              "Enregistre le personnage comme template de build (.txt) dans le dossier Templates.",
              "Saves the character as a build template (.txt) in the Templates folder."),
            R("Icône crayon", "Pencil icon",
              "Ouvre les propriétés du personnage (nom, notes, assignation, équipement).",
              "Opens the character properties (name, notes, assignment, equipment)."),
            R("Icône épées (⚔)", "Swords icon (⚔)",
              "Ouvre l'éditeur d'équipement du personnage.", "Opens the character's equipment editor."),
            R("Icône copier / importer", "Copy / import icon",
              "Copie le code de template du personnage, ou (build vide) colle un code depuis le presse-papier ou un fichier.",
              "Copies the character's template code, or (empty build) pastes a code from the clipboard or a file."),
            R("Clic sur le nom du joueur assigné", "Click the assigned player name",
              "Ouvre le menu du personnage (assignation, etc.).", "Opens the character menu (assignment, etc.)."),
            R("Clic droit sur la ligne du personnage", "Right-click the character row",
              "Menu complet : ajouter un personnage, propriétés, équipement, importer/copier les templates (O : compétences, P : équipement), assigner un joueur, échanger / déplacer / copier vers un autre personnage, créer une variante, verrouiller des variantes, vider le build, supprimer.",
              "Full menu: add character, properties, equipment, import/copy templates (O: skills, P: equipment), assign a player, swap / move / copy to another character, create a variant, lock variants, clear the build, remove."),
            R("Supprimer les compétences / les points / le build", "Clear skills / points / build",
              "Vident le contenu du build SANS toucher au personnage : le nom, les professions, les notes, l'équipement et le joueur assigné restent. « Supprimer le build » fait les deux à la fois. Les points bonus posés à la main (rune, coiffe, consommable) partent avec les points de base ; les rangs de titre restent. Ctrl+Z rend les compétences et les points de base en un seul pas — mais pas les points bonus, qui n'entrent dans aucun historique. Aussi au clic droit dans la page d'un onglet Build.",
              "Empty the build's contents WITHOUT touching the character: name, professions, notes, equipment and assigned player stay. “Clear build” does both at once. Hand-set bonus points (rune, headgear, consumable) go along with the base points; title ranks stay. Ctrl+Z brings back the skills and base points in one step — but not the bonus points, which are part of no history. Also on right-click in the page of a Build tab.")),

        // ═══════════════ FLUX, RITUELS, BOOSTS ═══════════════
        S("Flux, rituels et bonus temporaires", "Flux, rituals and temporary bonuses",
          "Ces bascules simulent un contexte de jeu : elles changent les infobulles, les niveaux de caractéristique et le calcul de spike, sans modifier les compétences équipées.",
          "These toggles simulate a game context: they change tooltips, attribute ranks and the spike calculus, without touching the equipped skills.",
            R("Icône de flux (build)", "Flux icon (build)",
              "Montre le flux actif ; clic pour l'activer ou le désactiver. Grise = inactif. Le flux est enregistré avec le team build.",
              "Shows the active flux; click to activate or deactivate it. Greyed = inactive. The flux is saved with the team build."),
            R("Bandeau des Rituels de la Nature", "Nature Rituals bar",
              "Une icône par rituel équipé par l'équipe (ou les 8 avec « Afficher tous ») ; clic = activer/désactiver. Cadre vert = actif.",
              "One icon per ritual equipped by the team (or all 8 with “Show all”); click = toggle. Green frame = active."),
            R("Molette sur Roaring Winds / Tranquility", "Wheel on Roaring Winds / Tranquility",
              "Règle le rang simulé (badge sur l'icône) quand aucun personnage équipé ne l'impose. Si un porteur l'a équipé, c'est son rang le plus fort qui gagne.",
              "Sets the simulated rank (badge on the icon) when no equipped character dictates it. If a carrier has it equipped, their highest rank wins."),
            R("Icône horloge (personnage)", "Clock icon (character)",
              "Active les prolongateurs de durée d'enchantement du personnage (Blessed Aura / Extend Enchantments). Se combine avec le mod d'arme « of Enchanting » et Tranquility.",
              "Enables the character's enchantment duration extenders (Blessed Aura / Extend Enchantments). Combines with the “of Enchanting” weapon mod and Tranquility."),
            R("Bandeau de bonus de caractéristique", "Attribute bonus bar",
              "Une icône par compétence équipée qui monte des caractéristiques (Aura of the Lich, Awaken the Blood, Elemental Attunement…) ; clic = activer. Le bonus apparaît en violet dans les attributs.",
              "One icon per equipped skill that raises attributes (Aura of the Lich, Awaken the Blood, Elemental Attunement…); click = activate. The bonus shows in purple in the attributes."),
            R("Maître de la magie", "Master of Magic",
              "Seul cas où la valeur est IMPOSÉE et non ajoutée : les caractéristiques élémentaires passent à « Fixé à X » (ambre), les bonus additifs restant appliqués par-dessus.",
              "The only case where the value is FORCED rather than added: elemental attributes become “Fixed at X” (amber), with additive bonuses still applied on top."),
            R("Heroic Refrain", "Heroic Refrain",
              "Équipée par n'importe quel membre de l'équipe, elle apparaît dans le bandeau de TOUS les personnages : chacun choisit s'il la reçoit, au rang de Charisme du lanceur le plus fort.",
              "Equipped by any member of the team, it appears in EVERY character's bar: each one chooses whether to receive it, at the highest caster's Leadership rank.")),

        // ═══════════════ CONDITIONS ═══════════════
        S("Conditions infligeables (bandeau)", "Inflictable conditions (bar)",
          "Les 10 conditions GW1, sous le build dans l'éditeur et en ligne unique au-dessus du team build (agrégat de l'équipe). Le bandeau suit le filtre PvE/PvP du catalogue.",
          "The 10 GW1 conditions, under the build in the editor and as a single row above the team build (team aggregate). The bar follows the catalog's PvE/PvP filter.",
            R("Icône en couleur", "Colored icon",
              "Une compétence équipée peut infliger la condition. Survol : lesquelles.",
              "An equipped skill can inflict the condition. Hover: which ones."),
            R("Icône grisée", "Greyed icon",
              "Aucune compétence équipée ne l'inflige, mais le combo PR/SEC y a accès dans le catalogue. Survol : description de la condition.",
              "No equipped skill inflicts it, but the primary/secondary combo has access to it in the catalog. Hover: condition description."),
            R("Icône quasi-éteinte", "Nearly-off icon",
              "Inaccessible à ce combo de professions.", "Not reachable by this profession combo."),
            R("Conditions auto-infligées", "Self-inflicted conditions",
              "Une condition que la compétence inflige au lanceur (ex. Signet of Agony) ne compte que si une compétence de transfert est aussi présente : Plague Sending, Plague Touch, Plague Signet, Contagion, Grenth's Fingers, Grenth's Grasp.",
              "A condition a skill inflicts on its caster (e.g. Signet of Agony) only counts when a transfer skill is present too: Plague Sending, Plague Touch, Plague Signet, Contagion, Grenth's Fingers, Grenth's Grasp.")),

        // ═══════════════ VARIANTES ═══════════════
        S("Variantes et cadenas", "Variants and locks",
          "Une variante est une copie indépendante d'un personnage, affichée en retrait sous lui. Les cadenas regroupent des variantes qui vont ensemble.",
          "A variant is an independent copy of a character, shown indented under it. Locks group variants that belong together.",
            R("Créer une variante (clic droit)", "Create variant (right-click)",
              "Duplique le personnage en une variante enfant modifiable indépendamment.",
              "Duplicates the character into a child variant that can be edited independently."),
            R("▶ / ▼", "▶ / ▼",
              "Replie / déploie les variantes d'un personnage.", "Collapses / expands a character's variants."),
            R("↑ / ↓", "↑ / ↓",
              "Réordonne une variante parmi ses sœurs.", "Reorders a variant among its siblings."),
            R("↩", "↩",
              "Échange une variante avec son parent (place et enfants inclus).",
              "Swaps a variant with its parent (position and children included)."),
            R("Case « Compétences héritées »", "“Inherited Skills” box",
              "Affiche les slots d'une variante identiques au parent en diagonale barrée (au lieu de l'icône réelle).",
              "Shows variant slots identical to the parent as barred squares (instead of the real icon)."),
            R("Verrouiller des variantes entre elles", "Lock variants together",
              "Ouvre le mode sélection : cochez les personnages à regrouper, puis Valider. Un cadenas coloré et indexé apparaît en tête de ligne.",
              "Opens selection mode: tick the characters to group, then Confirm. A colored, indexed lock appears at the start of the row."),
            R("Boutons de cadenas (barre du bas)", "Lock buttons (bottom bar)",
              "Filtrent l'affichage sur les membres d'un cadenas ; « Vue complète » revient à tout afficher.",
              "Filter the view to a lock's members; “Full view” shows everything again."),
            R("Clic droit sur une barre de cadenas", "Right-click a lock bar",
              "Éditer / Supprimer le cadenas, ou l'Exporter (membres seuls) en .pn3, .png ou chat codes .txt (O+P).",
              "Edit / Remove the lock, or Export it (members only) as .pn3, .png or .txt chat codes (O+P).")),

        // ═══════════════ CATALOGUE ═══════════════
        S("Catalogue de compétences", "Skill catalog",
          "Panneau de droite de l'éditeur. Source des compétences à glisser dans les slots. Noms et descriptions suivent la langue de l'application.",
          "Right-hand panel of the editor. Source of the skills you drag into the slots. Names and descriptions follow the application language.",
            R("Colonnes Professions / Caractéristiques / PvE only",
              "Professions / Attributes / PvE only columns",
              "Filtrent la liste par profession, par caractéristique, ou par catégorie de compétences PvE.",
              "Filter the list by profession, by attribute, or by PvE skill category."),
            R("Lignes Types de compétences / Mécaniques", "Skill Types / Mechanics rows",
              "Deux lignes de puces sous les professions, qu'on affiche depuis le menu Affichage ou par les cases de la barre de recherche. « Types de compétences » reprend ce que dit l'infobulle du jeu (Sort, Sceau, Attaque d'arc…) ; « Mécaniques » ce que la compétence fait (adrénaline, épuisement, blocage, poses, Ordres…). Repliée, la ligne ne montre que la puce active ; un clic dessus la déplie. Les deux filtres se combinent entre eux et avec tous les autres.",
              "Two chip rows under the professions, shown from the View menu or with the search bar's tick boxes. “Skill Types” mirrors what the in-game tooltip says (Spell, Signet, Bow Attack…); “Mechanics” what the skill does (adrenaline, exhaustion, blocking, stances, Orders…). Folded, a row only shows the active chip; clicking it unfolds the row. Both filters combine with each other and with all the others."),
            R("Ligne « Catégories : … »", "“Categories: …” line",
              "Sous la recherche : les catégories reconnues dans ce que vous tapez — écrire « enchantement » ou « aveuglement » filtre directement dessus — puis, s'il y a lieu, le nombre de compétences que les filtres actifs masquent, avec un clic pour lever ces filtres.",
              "Under the search box: the categories recognized in what you type — typing “enchantment” or “blindness” filters on them straight away — then, where relevant, how many skills the active filters hide, with a click to lift those filters."),
            R("Menu déroulant PvE/PvP", "PvE/PvP dropdown",
              "Restreint le catalogue à toutes les compétences, aux PvE uniquement, ou aux PvP uniquement.",
              "Restricts the catalog to all skills, PvE only, or PvP only."),
            R("Rechercher", "Search skills",
              "Filtre la liste par nom, en temps réel, dans la langue affichée.",
              "Filters the list by name, live, in the displayed language."),
            R("Clic sur un en-tête de colonne", "Click a column header",
              "Trie la liste (Nom, E, A, S, O, U, C, R). Un second clic inverse le sens.",
              "Sorts the list (Name, E, A, S, O, U, C, R). A second click reverses the order."),
            R("Glisser une ligne", "Drag a row",
              "Dépose la compétence dans un slot de personnage.", "Drops the skill into a character slot."),
            R("Clic droit sur une ligne", "Right-click a row",
              "Article de la compétence, Page de discussion, Chercher dans les templates.",
              "Skill article, Skill discussion, Parse in templates.")),

        // ═══════════════ BROWSER ═══════════════
        S("Browser (onglet Team Builds)", "Browser (Team Builds tab)",
          "Explorateur de vos fichiers de builds : arbre de dossiers, liste des fichiers, et preview du fichier sélectionné.",
          "Explorer for your build files: folder tree, file list, and preview of the selected file.",
            R("Double-clic / Entrée", "Double-click / Enter",
              "Ouvre le fichier sélectionné dans un onglet.", "Opens the selected file in a tab."),
            R("Parcourir…", "Browse…",
              "Change le dossier racine affiché (mémorisé entre les sessions).",
              "Changes the displayed root folder (remembered between sessions)."),
            R("Clic sur un en-tête", "Click a header",
              "Trie la liste des fichiers (nom, format, joueurs, campagnes, date).",
              "Sorts the file list (name, format, players, campaigns, date)."),
            R("Clic droit sur un fichier", "Right-click a file",
              "Renommer, Supprimer (corbeille), Copier (presse-papier), Importer ici…, Exporter…",
              "Rename, Delete (recycle bin), Copy (clipboard), Import here…, Export…"),
            R("Preview d'un team build", "Team build preview",
              "Les barres de compétences des personnages principaux ; survol d'une icône = infobulle complète.",
              "The skill bars of the main characters; hovering an icon shows the full tooltip."),
            R("Preview d'un template .txt", "…txt template preview",
              "Colonnes Profession, Profession secondaire, Meilleure caractéristique secondaire et Compétence élite, avec un bouton pour copier la barre en chat code.",
              "Primary profession, secondary profession, highest secondary attribute and elite skill columns, with a button to copy the bar as a chat code.")),

        // ═══════════════ RECHERCHE ═══════════════
        S("Recherche de templates", "Template search",
          "Trouve, parmi vos fichiers, les templates qui contiennent certaines compétences et satisfont des seuils d'attributs.",
          "Finds, among your files, the templates that contain given skills and meet attribute thresholds.",
            R("Perso-requête (professions + 8 slots)", "Query character (professions + 8 slots)",
              "Composez la requête comme un personnage : glissez les compétences recherchées dans les slots.",
              "Build the query like a character: drag the skills you look for into the slots."),
            R("Seuils d'attributs (≥ / ≤)", "Attribute thresholds (≥ / ≤)",
              "Fixez un seuil par caractéristique ; cliquez le glyphe pour basculer « au moins » (≥) / « au plus » (≤).",
              "Set a threshold per attribute; click the glyph to toggle “at least” (≥) / “at most” (≤)."),
            R("Cases Templates (.txt) / Teambuilds (.pn3 / .pwnd)", "Templates (.txt) / Teambuilds (.pn3 / .pwnd) boxes",
              "Choisissent les types de fichiers inclus dans la recherche.",
              "Choose which file types the search includes."),
            R("Cadres rouges dans la requête", "Red frames in the query",
              "Les compétences demandées exigent plus de professions qu'un personnage n'en a : fixez une profession ou retirez une compétence, sinon la recherche reste bloquée.",
              "The requested skills need more professions than a character has: pin a profession or drop a skill, otherwise the search stays disabled."),
            R("Lancer la recherche", "Run search",
              "Ouvre un onglet « Résultats » listant les fichiers correspondants.",
              "Opens a “Results” tab listing the matching files.")),

        // ═══════════════ ÉQUIPEMENT ═══════════════
        S("Éditeur d'équipement", "Equipment editor",
          "Ouvert par l'icône ⚔ d'un personnage, par son menu contextuel, ou par Fichier ▸ Nouveau template d'équipement. Le résultat est un code d'équipement (P), indépendant du code de compétences (O).",
          "Opened from a character's ⚔ icon, from its context menu, or from File ▸ New Equipment Template. The result is an equipment code (P), independent from the skill code (O).",
            R("Liste des emplacements", "Slot list",
              "Les 5 pièces d'armure et les mains ; sélectionnez un emplacement pour l'éditer à droite.",
              "The 5 armor pieces and the hands; select a slot to edit it on the right."),
            R("Onglets F1 – F4", "F1 – F4 tabs",
              "Les 4 sets d'armes du personnage, comme en jeu.", "The character's 4 weapon sets, as in game."),
            R("Profession et genre", "Profession and gender",
              "Déterminent les armures et les skins proposés ; le genre est enregistré dans le fichier.",
              "Drive the armor sets and skins offered; the gender is saved in the file."),
            R("Objet, ×5, 🔗 Wiki", "Item, ×5, 🔗 Wiki",
              "Choix de la pièce ; ×5 applique le style à toutes les pièces (la coiffe, choix d'attribut, n'est pas touchée) ; le lien ouvre la page wiki.",
              "Piece choice; ×5 applies the style to every piece (the headgear, an attribute choice, is left untouched); the link opens the wiki page."),
            R("Insigne, Rune, Inscription, Préfixe, Suffixe", "Insignia, Rune, Inscription, Prefix, Suffix",
              "Les mods disponibles pour l'emplacement et la profession. ×5 applique l'insigne à toutes les pièces d'armure.",
              "The mods available for the slot and profession. ×5 applies the insignia to every armor piece."),
            R("Teinture", "Dye", "Couleur de la pièce (cosmétique).", "Piece color (cosmetic only)."),
            R("Barre de stats", "Stats bar",
              "Bonus d'attributs, PV, énergie, pips de régénération et armure résultants.",
              "Resulting attribute bonuses, health, energy, regeneration pips and armor."),
            R("Bouclier", "Shield",
              "Entre parenthèses : l'armure obtenue si le requis n'est pas atteint (moitié seulement). Le bouclier de Force donne alors +9 au lieu de +8 — bug du jeu, reproduit ici.",
              "In parentheses: the armor obtained if the requirement is not met (half only). The Strength shield then gives +9 instead of +8 — a game bug, reproduced here."),
            R("Charger / Sauvegarder comme template", "Load / Save as template",
              "Relit ou enregistre un équipement complet dans un fichier .txt réutilisable.",
              "Reloads or stores a complete equipment set in a reusable .txt file.")),

        // ═══════════════ CALCULATEUR D'ARMURE ═══════════════
        S("Calculateur d'armure", "Armor calculator",
          "Onglet Armure (Extras ▸ Calculateur d'armure) : reconstitue l'AL effective d'un personnage, pièce par pièce et type de dégâts par type de dégâts, puis chiffre ce que coûtent les attaques.",
          "Armor tab (Extras ▸ Armor calculator): reconstructs a character's effective AL, piece by piece and damage type by damage type, then quantifies what attacks actually deal.",
            R("Personnage & équipement", "Character & equipment",
              "Profession, AL de base, insigne de chaque pièce, bouclier (AL, requis rempli, bug du bouclier de Force).",
              "Profession, base AL, insignia of each piece, shield (AL, requirement met, Strength shield bug)."),
            R("Mods d'équipement", "Equipment mods",
              "Runes, mods d'armes et inscriptions, avec les limites réalistes du jeu : 5 runes, 1 inscription et 1 mod d'arme par main, le bouclier occupant la main secondaire.",
              "Runes, weapon mods and inscriptions, with the game's realistic limits: 5 runes, 1 inscription and 1 weapon mod per hand, the shield taking the off hand."),
            R("Coller un code d'équipement (P)", "Paste an equipment code (P)",
              "Remplit les insignes et le bouclier depuis un code existant.",
              "Fills insignia and shield from an existing code."),
            R("État du personnage", "Character state",
              "Les cases (enchanté, maléfice, pose de combat, en attaque…) et les compteurs (PV %, enchantements, recharges, serviteurs, esprits, sceaux, compétences Illusion) déclenchent les insignes conditionnelles.",
              "The boxes (enchanted, hexed, in stance, attacking…) and counters (HP %, enchantments, recharging skills, minions, spirits, signets, Illusion skills) drive conditional insignia."),
            R("Sources externes", "External sources",
              "Compétences alliées, malus subis, consommables et effets : cochez ce qui s'applique.",
              "Allied skills, incoming penalties, consumables and effects: tick whatever applies."),
            R("Grille d'AL effective", "Effective AL grid",
              "AL par pièce et par type de dégâts. Clic sur une cellule = détail pas à pas du calcul ; re-clic = retour à la moyenne.",
              "AL per piece and damage type. Click a cell for the step-by-step breakdown; click again to return to the mean."),
            R("Espérance (moyenne pondérée)", "Expectancy (weighted mean)",
              "AL équivalente d'un personnage ciblé au hasard : torse 3/8, jambes 2/8, tête, bras et pieds 1/8 chacun.",
              "Equivalent AL for a randomly targeted character: chest 3/8, legs 2/8, head, arms and feet 1/8 each."),
            R("Réductions de durée d'altération", "Condition duration reductions",
              "Récapitule ce que les runes et mods actifs retirent à chaque altération.",
              "Sums up what the active runes and mods remove from each condition."),
            R("Attaques de référence", "Reference attacks",
              "Ajoutez des compétences depuis le catalogue (double-clic, Entrée ou « + Ajouter ») : dégâts @ AL 60 et @ AL du build, rang réglable, altérations infligées avec leur durée effective.",
              "Add skills from the catalog (double-click, Enter or “+ Add”): damage @ AL 60 and @ build AL, adjustable rank, inflicted conditions with their effective duration."),
            R("Filtres du catalogue d'attaques", "Attack catalog filters",
              "Profession, caractéristique, mode de jeu, « dégâts seulement », puis les mêmes catégories que le catalogue de compétences : Types de compétences et Mécaniques, ici en listes déroulantes toujours affichées.",
              "Profession, attribute, game mode, “damage only”, then the same categories as the skill catalog: Skill Types and Mechanics, here as dropdowns that are always on screen."),
            R("Profils", "Profiles",
              "Enregistrent l'ensemble des réglages sous un nom pour les recharger plus tard.",
              "Save the whole set of settings under a name to reload later.")),

        // ═══════════════ SPIKE ═══════════════
        S("Spike damage calculus", "Spike damage calculus",
          "Bouton ⚡ Spike, en bas du team build : additionne les dégâts des compétences choisies, lancées ensemble sur une même cible. Le roster et la sélection sont enregistrés dans le fichier.",
          "⚡ Spike button, at the bottom of the team build: adds up the damage of the chosen skills, cast together on a single target. Roster and selection are saved in the file.",
            R("Roster (8 lignes max)", "Roster (max 8 rows)",
              "Cochez les personnages à inclure (racines ou variantes) avec les mêmes cases que les cadenas.",
              "Tick the characters to include (roots or variants) with the same boxes as the locks."),
            R("Clic sur une compétence", "Click a skill",
              "La compte dans le spike (cadre vert) ; recliquez pour la retirer.",
              "Counts it in the spike (green frame); click again to remove it."),
            R("Pastille verte numérotée", "Numbered green badge",
              "Rappelle l'ordre des clics, c'est-à-dire l'ordre de cast — utilisé par le flux Chain Combo.",
              "Recalls the click order, that is the cast order — used by the Chain Combo flux."),
            R("Procs / Ticks", "Procs / Ticks",
              "Nombre d'occurrences comptées : coups d'une attaque répétée, déclenchements d'un rider, ou ticks d'un effet périodique (Fire Storm, pièges…). Savannah Heat est cumulative : le tick n inflige n × la valeur.",
              "Number of occurrences counted: hits of a repeated attack, rider triggers, or ticks of a periodic effect (Fire Storm, traps…). Savannah Heat is cumulative: tick n deals n × the value."),
            R("Seuil / Condition remplie", "Threshold / Condition met",
              "Pour les compétences à part conditionnelle (cible sous un seuil de PV, sous condition…) : décide si le bonus compte.",
              "For skills with a conditional part (target below an HP threshold, under a condition…): decides whether the bonus counts."),
            R("Type de dégâts de l'arme", "Weapon damage type",
              "Se choisit par attaque, sur sa ligne : mod élémentaire, skin particulier, ou changement d'arme en cours de spike.",
              "Chosen per attack, on its row: elemental mod, special skin, or a weapon switch mid-spike."),
            R("Mod d'arme", "Weapon mod",
              "Mod de préfixe physique de l'attaque : de fractionnement ou vampirique. Il occupe le même emplacement qu'un mod élémentaire — choisir un type de dégâts élémentaire le remet à « Aucun ». Les autres types de la liste sont des skins et laissent le préfixe libre.",
              "The attack's physical prefix mod: Sundering or Vampiric. It uses the same slot as an elemental mod — picking an elemental damage type resets it to \"None\". The other types in the list are skins and leave the prefix free."),
            R("Proc du fractionnement / Arc corne", "Sundering proc / Hornbow",
              "Deux pénétrations d'armure en bonus, qui s'ajoutent aux autres (Judge's Insight compris) : +20 % quand le fractionnement se déclenche — comptés sur toute la ligne, frappes multiples incluses —, et +10 % en permanence pour un arc corne.",
              "Two bonus armor penetrations, which add on top of the others (Judge's Insight included): +20% when Sundering triggers — counted for the whole row, multiple strikes included — and a permanent +10% for a hornbow."),
            R("Lignes « Vol de vie »", "\"Life Stealing\" rows",
              "Déclarer un mod vampirique n'ajoute rien à sa ligne : cela fait apparaître en fin de liste une ligne globale par valeur de vol (3 à une main, 5 à deux mains). À vous d'y compter toutes les attaques vampiriques qui touchent, celles du spike comprises ; 0 affiche la ligne sans la compter.",
              "Declaring a vampiric mod adds nothing to its own row: it makes a global row appear at the end of the list, one per steal value (3 one-handed, 5 two-handed). You count there every vampiric attack that lands, including the spike's own; 0 shows the row without counting it."),
            R("Buffs (icônes)", "Buffs (icons)",
              "Buffs d'arme du lanceur (Splinter Weapon, Great Dwarf Weapon, Orders…) : activez ceux qui portent au moment du spike.",
              "The caster's weapon buffs (Splinter Weapon, Great Dwarf Weapon, Orders…): enable those active at spike time."),
            R("Colonne Bonus Flux", "Flux bonus column",
              "Part de dégâts due au flux actif, séparée du reste.",
              "Share of the damage due to the active flux, kept separate."),
            R("PV lanceur", "Caster HP",
              "PV courants et max du lanceur : servent au vol de vie (plafonné) et à Grenth's Balance.",
              "The caster's current and max HP: used for life steal (capped) and Grenth's Balance."),
            R("Panneau Cible", "Target panel",
              "AL de base et bonus d'AL par groupe et par type (ils se cumulent), niveau (taux de critique), PV max et courants, profession principale (flux Amateur Hour / There Can Be Only One).",
              "Base AL and AL bonuses per group and per type (they stack), level (critical hit rate), max and current HP, primary profession (Amateur Hour / There Can Be Only One flux)."),
            R("Profils de cible", "Target profiles",
              "Enregistrent une cible complète sous un nom.", "Save a complete target under a name."),
            R("Blessure profonde / Armure brisée / Tout en critique",
              "Deep Wound / Cracked Armor / All crits",
              "Modulent le total : +min(20 % des PV max, 100), −20 AL (plancher 60), et toutes les attaques d'arme en coup critique.",
              "Modulate the total: +min(20% of max HP, 100), −20 AL (floor 60), and all weapon attacks as critical hits."),
            R("Copier l'image", "Copy image",
              "Copie une capture de la fenêtre entière dans le presse-papiers.",
              "Copies a screenshot of the whole window to the clipboard.")),

        // ═══════════════ FICHIERS ═══════════════
        S("Fichiers, formats et données", "Files, formats and data", "", "",
            R(".pn3", ".pn3",
              "Format natif de Z-Codex : un team build complet (personnages, variantes, cadenas, attributs, équipement, flux, rituels, roster de spike).",
              "Z-Codex's native format: a complete team build (characters, variants, locks, attributes, equipment, flux, rituals, spike roster)."),
            R(".pwnd", ".pwnd",
              "Team builds de paw·ned², lus ET écrits. Fichier → « Exporter en paw·ned² » propose trois portées : tout le teambuild (variantes comprises), les 8 premiers personnages, ou un cadenas ; le sous-menu Exporter d'un cadenas propose la même sortie. Le format ne transporte que professions, attributs et 8 compétences : noms, équipement, notes et cadenas ne suivent pas. paw·ned² écrit toujours 8 emplacements — en dessous Z-Codex complète avec des emplacements vides, au-dessus il en écrit autant que nécessaire.",
              "paw·ned² team builds, read AND written. File → “Export to paw·ned²” offers three scopes: the whole team build (variants included), the first 8 characters, or one lock; a lock's Export submenu offers the same output. The format only carries professions, attributes and 8 skills: names, equipment, notes and locks do not follow. paw·ned² always writes 8 slots — below that Z-Codex pads with empty slots, above it writes as many as needed."),
            R(".txt (code O)", ".txt (O code)",
              "Template de compétences du jeu : professions, attributs et 8 compétences. Import/export via le presse-papier ou un fichier.",
              "The game's skill template: professions, attributes and 8 skills. Import/export through the clipboard or a file."),
            R(".txt (code P)", ".txt (P code)",
              "Template d'équipement du jeu, indépendant du code de compétences.",
              "The game's equipment template, independent from the skill code."),
            R("Données locales", "Local data",
              "Catalogue de compétences, icônes et réglages vivent dans %AppData%\\Z-Codex. Le catalogue provient du Guild Wars Wiki ; l'application propose une mise à jour quand elle détecte un patch du jeu.",
              "The skill catalog, icons and settings live in %AppData%\\Z-Codex. The catalog comes from the Guild Wars Wiki; the application offers an update when it detects a game patch.")),
    };
}
